### ISSUE TITLE
PEP 518 / Poetry / pyproject.toml

### ISSUE THREAD

**Issue by interrogator** [bitpanda-labs/loggo#104]
From black docs:

```
What on Earth is a pyproject.toml file?

PEP 518 defines pyproject.toml as a configuration file to store build system requirements for Python projects. With the help of tools like Poetry or Flit it can fully replace the need for setup.py and setup.cfg files.
```

PEP 518: https://www.python.org/dev/peps/pep-0518/

Poetry: https://poetry.eustace.io/

Consider setting up something like this? Especially since we have black running?

**Comment by hukkinj1** [comment]
Currently I don't think we need or want this. 

- We have exactly one dependency. There's not much of a chance for conflicts or solving that issue.
- Poetry complicates .travis.yml slightly
- Poetry takes a lot longer to install dependencies than just pip
- Breaks the "clone the repo and `python setup.py install`" install workflow instructed in the README.
- Don't think black should in any way be involved in this discussion, it just happens to use the same file for configuration.

Overall I think we don't have a problem that poetry would solve in this project, and `setup.py` is the most compatible way to set up a library today.

**Comment by interrogator** [comment]
Yeah, while it seems like poetry may help out for projects with complex dependencies, ours are simple so we best go with the standard. In truth I had never heard of it till reading through black docs --- I just figured since we at this repo are black fanboys we might like to consider this ;) Happy to close

**Comment by hukkinj1** [comment]
Haha, true we are huge black fanboys, and personally am also a poetry fanboy. But despite it being a great tool, don't think it's the correct tool for this project.
