### ISSUE TITLE
Loggo throws when `inspect.signature()` fails to get function/method signature

### ISSUE THREAD

**Issue by hukkinj1** [bitpanda-labs/loggo#15]
`inspect.signature()` is run for Loggo-decorated functions. There's no knowing that it succeeds in getting the signature for all callables however. It may throw ValueError. Try for example `inspect.signature(print)`. Result: ValueError.
My suggestion: We simply don't log functions where `inspect.signature()` fails, silently eat the ValueError, and clearly document this limitation in the README and code.

**Comment by interrogator** [comment]
Yeah, I was in two minds about error logs for loggo internal errors. I've never bumped into this and it sounds like you have, so how about a bloody PR?

**Comment by interrogator** [comment]
Simple fix in bef0db3
