### ISSUE TITLE
TRAVIS

### ISSUE THREAD

**Issue by interrogator** [bitpanda-labs/loggo#25]
@jorop to set up travis CI to run tests unless there is nowadays a nicer way like we got with gitlab

**Comment by interrogator** [comment]
hey @jorop what's this business: https://travis-ci.org/bitpanda-labs/loggo/jobs/470605700

```
----------------------------------------------------------------------
Ran 30 tests in 3.114s
OK
The command "python tests/tests.py" exited with 0.
Done. Your build exited with 1.
```

lol

**Comment by jorop** [comment]
line 460. issue when executing `flake8 loggo` which didn't exit properly. the pipeline did continue, which is different than gitlab-ci.

**Comment by interrogator** [comment]
OK, then there is no issue. Closing.
