### ISSUE TITLE
Time to remove emergency log?

### ISSUE THREAD

**Issue by interrogator** [bitpanda-labs/loggo#40]
`_emergency_log()` has been around for years and for historical reasons. @hukkinj1 you think we should just remove it? there is an option to raise/not raise errors during logging, i'd probably rather just use that and potentially raise instead.

**Comment by hukkinj1** [comment]
Looks to me like I fully agree that it should be removed. It only gets run when self.logger.log() raises and self.logger is always a logging.Logger. Dont think that ever raises (unless giving somehow invalid args or something, meaning its a Loggo bug, meaning Loggo should raise IMO)

**Comment by interrogator** [comment]
Great minds

**Comment by interrogator** [comment]
Done in a3729583bd7c9809eb1c5009fb8e3dfb78a3313b
