### ISSUE TITLE
Getting a "WARNING: Should not use key "args" in log data" log when using @Loggo.errors

### ISSUE THREAD

**Issue by hukkinj1** [bitpanda-labs/loggo#6]
Got this warning log despite not adding anything manually to "log data". If this is a problematic key, would it be nicer if loggo handled it internally, instead of logging a warning?

**Comment by interrogator** [comment]
If I remember correctly, you can pass arbitrary args and kwargs to the python logger.logger on which loggo Is built. If you do this with some names, like `args`, or `message`, it throws an error when you call the logger. To get around this, loggo looks for such names, warns if there, and turns (e.g.) `args` into `protected_args`.

`_rename_protected_keys` is the function that does this. I think the only real improvement that could be made Is to have a config value `warn_on_reserved_name` ... PR welcome!

**Comment by interrogator** [comment]
But yeah, I get your point, a bit rude to be warned when you didn't actually write any naughty logs, it just read function signatures...

**Comment by interrogator** [comment]
OK, compromise, you no longer get the warning  for 'args', because it's the standard way of representing unnamed position arguments, but for other naughty keys you still do.

**Comment by interrogator** [comment]
Only problem is that now your `args` will show up in graylog as `protected_args` and unless you read this issue you might not know why. oh well 🇦🇹

**Comment by hukkinj1** [comment]
How about a "Limitations" section in the README where stuff like this is documented?

**Comment by interrogator** [comment]
Yeah, that is the best way. I'll implement today, basically blaming limitations in the standard library.
