### ISSUE TITLE
Explicit inherit from object?

### ISSUE THREAD

**Issue by interrogator** [bitpanda-labs/loggo#62]
`class Loggo(object):` or `class Loggo:`? Believe we aren't maintaining Python 2 compatibility? @gcarq?

**Comment by hukkinj1** [comment]
`class Loggo:` please. We were never supposed to have Python 2 compatibility in the first place. `setup.py` says `python_requires='>=3',`

**Comment by hukkinj1** [comment]
Made the change here https://github.com/bitpanda-labs/loggo/pull/61

**Comment by interrogator** [comment]
Done. Lucky we had all three of us for this one.
