### ISSUE TITLE
Discussion: Use typehints?

### ISSUE THREAD

**Issue by hukkinj1** [bitpanda-labs/loggo#63]
Should we use typehints and require Python version to be >=3.6 ? I vote yes.

**Comment by interrogator** [comment]
OK, fine by me, though it'll prob take @gcarq 5 minutes if he wants to do it

**Comment by hukkinj1** [comment]
Ok, decided it is, then. Implementation will happen here https://github.com/bitpanda-labs/loggo/issues/64
