### ISSUE TITLE
Alert level semantics: your ultimate guide

### ISSUE THREAD

**Issue by interrogator** [bitpanda-labs/loggo#68]
### Make yourself a cup of tea and consider:

Any time you log, whether you like it or not, there is an 'alert level', But what does it mean? It's actually surprisingly complex. We have to ask ourselves, why is there an alert? For whom? And what does changing such a level do? What *can* it do? What *could* it do?

Python's `logging` module (which we draw upon right now) has what we might call 'named numbers':

CRITICAL | 50
-- | --
ERROR | 40
WARNING | 30
INFO | 20
DEBUG | 10
NOTSET | 0

These are supposed to represent a kind of scale of severity. Adding confusion, our code had to deal with bitpanda legacy features, and graylog compatibility. This is why Loggo allows us to pass strings, `minor`, `dev` and `critical`, as alert level.

We likely all agree that having multiple level types is a bad idea, but it's interesting to consider why it happened in the first place.

In short, there is an ever-present question of what the semantics of the numeric scale actually *mean*: should the scale progress from `expected --> unexpected`, from `good --> bad`, or `common --> rare`?

Competing standards arose to address these ambiguities. Then, compounding the problem a great deal was that that nobody really gives a shit about logging, and accordingly, nobody ever confronted the complexity of this ridiculous question.

One certainty, therefore, is that we will never do things right in an ontological sense. Internally consistent and expressive code would ideally handle multiple *types* of alert levels, with a multifaceted set of sequences. Imagine the joy and horror of:

```python
log('overkill', expectedness=6, severity=2, badness=9)
```

Fortunately for us, however, the different types of alerts tend to pattern together. Unless a product really sucks a lot, you would not its logs to have high values for `expectedness`, `severity` and `badness` all at once. These things all mean different things, but they seem to overlap more than they don't. So, we're back to square one, only now we know that our implementation will stink.

### What to do now: the wrong way

There is an obvious pathway for improving our alert level handling. That is to remove from Loggo the ability to handle legacy bitpanda/graylog stuff, such as `'minor'`, `'dev'` and `'critical'` strings. Instead, the user should use the integer defined in the `logging` module.

To make things a bit nicer, we can also do two other things:

1. Make available `Loggo.DEBUG == 10` and so on. I don't want to import `loggo` and `logging`, and I think at least at times, using the namespaced values is easier to understand than e.g., a random `50`, which means critical.
2. Allow the call signature from `logging` --- `log(10, 'msg', data)`:

```python
if isinstance(msg, int) and isinstance(level, str):
    msg, level = level, msg
```

Bitpanda's subclasses of Loggo can, if they like, interpret the deprecated strings, and derive `graylog` data from them if need be. None of my business really.

### What to do: the right way

1. Read this document: https://tools.ietf.org/html/rfc5424
2. Internalise its teachings
3. See if we can solve the complexities outlined above in a fantastic and novel way
4. When this fails, just do `the wrong way`
5. Sauna whenever possible

**Comment by hukkinj1** [comment]
Haha, what a great issue. My first thought is nobody has time to read https://tools.ietf.org/html/rfc5424 and we still use `logging` stdlib underlyingly, so might just support its log levels. So implement `the wrong way`.

**Comment by interrogator** [comment]
plz print our two copies to go over in the sauna tonight

**Comment by interrogator** [comment]
OK, happy for panda to begin implementation of `the wrong way`; breaks compat with their code until subclassing is updated, so someone outside the organisation doing it is a no-no right now

**Comment by hukkinj1** [comment]
Implemented `the wrong way` here https://github.com/bitpanda-labs/loggo/pull/70

**Comment by hukkinj1** [comment]
`the wrong way` merged. Closing.
