### ISSUE TITLE
Combine Loggo() and loggo.events

### ISSUE THREAD

**Issue by interrogator** [bitpanda-labs/loggo#80]
* Remove loggo.events, which has very similar code to `logme` anyway
* Add its functionality to the line where Loggo is instantiated with config: `loggo = Loggo(config, called='custom message --- {timestamp}, {call_signature}')`
* Change internal names `pre` -> `called` etc now that they are exposed to user
* If user explicitly passes `called=None`, no logs for calling. Otherwise, existing defaults are used
* Document available formatting strings in README
* Move `error_alert_level` to config, default 50
* `build_string` no longer needed, `timestamp` and `trace` can be in the default format strings

This will reduce size of codebase, which is good.

**Comment by hukkinj1** [comment]
Done and merged here: https://github.com/bitpanda-labs/loggo/pull/81
